### ISSUE TITLE
some errors after compilation

### ISSUE THREAD

**Issue by BenMitnicK** [stefanounick/J-Runner#1]
Error	1	The name 'driveinfo' does not exist in the current context	C:\Users\Dev\Documents\Visual Studio 2012\Projects\J-Runner\J-Runner\MainForm.cs	168	13	JRunner
Error	2	The name 'driveinfo' does not exist in the current context	C:\Users\Dev\Documents\Visual Studio 2012\Projects\J-Runner\J-Runner\MainForm.cs	169	13	JRunner
Error	3	The name 'driveinfo' does not exist in the current context	C:\Users\Dev\Documents\Visual Studio 2012\Projects\J-Runner\J-Runner\MainForm.cs	170	13	JRunner
Error	4	The name 'driveinfo' does not exist in the current context	C:\Users\Dev\Documents\Visual Studio 2012\Projects\J-Runner\J-Runner\MainForm.cs	171	13	JRunner
Error	5	The name 'driveinfo' does not exist in the current context	C:\Users\Dev\Documents\Visual Studio 2012\Projects\J-Runner\J-Runner\MainForm.cs	172	13	JRunner
Error	6	The name 'driveinfo' does not exist in the current context	C:\Users\Dev\Documents\Visual Studio 2012\Projects\J-Runner\J-Runner\MainForm.cs	173	13	JRunner
Error	7	The name 'driveinfo' does not exist in the current context	C:\Users\Dev\Documents\Visual Studio 2012\Projects\J-Runner\J-Runner\MainForm.cs	174	13	JRunner
Error	8	The name 'driveinfo' does not exist in the current context	C:\Users\Dev\Documents\Visual Studio 2012\Projects\J-Runner\J-Runner\MainForm.cs	175	13	JRunner
Error	9	The name 'dTools' does not exist in the current context	C:\Users\Dev\Documents\Visual Studio 2012\Projects\J-Runner\J-Runner\MainForm.cs	177	13	JRunner
Error	10	The name 'dTools' does not exist in the current context	C:\Users\Dev\Documents\Visual Studio 2012\Projects\J-Runner\J-Runner\MainForm.cs	178	13	JRunner
Error	11	The name 'dTools' does not exist in the current context	C:\Users\Dev\Documents\Visual Studio 2012\Projects\J-Runner\J-Runner\MainForm.cs	179	13	JRunner

and more :(

**Comment by stefanounick** [comment]
you had some flags enabled
it should build correctly now

**Comment by BenMitnicK** [comment]
I have made the same modifications as you and the application this spear but there are bugs example Sonus editor crash the program and the loaded nand does not work and I have the same error with your modification because you removed what I had already removed but the program works if you run it directly outside visual studio lol so it's ok. Why did you remove the images tab?

**Comment by BenMitnicK** [comment]
hi,
you can empty you private message in teamxecuter forum because  " you has exceeded their stored private messages quota "  thx  :)
